import { Key } from '@nut-tree/nut-js';

const map: { [key: string]: Key } = {
  ' ': Key.Space,
  escape: Key.Escape,
  tab: Key.Tab,
  '⌥': Key.LeftAlt,
  '⌃': Key.LeftControl,
  //"⌥": Key.RightAlt,
  //"⌃": Key.RightControl,
  '⇧': Key.LeftShift,
  '⌘': Key.LeftSuper,
  //"⇧": Key.RightShift,
  //"⌘": Key.RightSuper,
  F1: Key.F1,
  F2: Key.F2,
  F3: Key.F3,
  F4: Key.F4,
  F5: Key.F5,
  F6: Key.F6,
  F7: Key.F7,
  F8: Key.F8,
  F9: Key.F9,
  F10: Key.F10,
  F11: Key.F11,
  F12: Key.F12,
  '0': Key.Num0,
  '1': Key.Num1,
  '2': Key.Num2,
  '3': Key.Num3,
  '4': Key.Num4,
  '5': Key.Num5,
  '6': Key.Num6,
  '7': Key.Num7,
  '8': Key.Num8,
  '9': Key.Num9,
  A: Key.A,
  B: Key.B,
  C: Key.C,
  D: Key.D,
  E: Key.E,
  F: Key.F,
  G: Key.G,
  H: Key.H,
  I: Key.I,
  J: Key.J,
  K: Key.K,
  L: Key.L,
  M: Key.M,
  N: Key.N,
  O: Key.O,
  P: Key.P,
  Q: Key.Q,
  R: Key.R,
  S: Key.S,
  T: Key.T,
  U: Key.U,
  V: Key.V,
  W: Key.W,
  X: Key.X,
  Y: Key.Y,
  Z: Key.Z,
  '`': Key.Grave,
  '-': Key.Minus,
  '=': Key.Equal,
  backspace: Key.Backspace,
  '[': Key.LeftBracket,
  ']': Key.RightBracket,
  '/': Key.Backslash,
  ';': Key.Semicolon,
  "'": Key.Quote,
  enter: Key.Return,
  ',': Key.Comma,
  '.': Key.Period,
  '//': Key.Slash,
  'arrow left': Key.Left,
  'arrow up': Key.Up,
  'allow right': Key.Right,
  'arrow down': Key.Down,
  print: Key.Print,
  pause: Key.Pause,
  insert: Key.Insert,
  delete: Key.Delete,
  home: Key.Home,
  end: Key.End,
  'page up': Key.PageUp,
  'page down': Key.PageDown,
  '+': Key.Add,
  //"-": Key.Subtract,
  '*': Key.Multiply,
  //"/": Key.Divide,
  //"": Key.Decimal,
  //"": Key.Enter,
  //"": Key.NumPad0,
  //"": Key.NumPad1,
  //"": Key.NumPad2,
  //"": Key.NumPad3,
  //"": Key.NumPad4,
  //"": Key.NumPad5,
  // "": Key.NumPad6,
  // "": Key.NumPad7,
  // "": Key.NumPad8,
  // "": Key.NumPad9,
  'caps lock': Key.CapsLock,
  'scroll lock': Key.ScrollLock,
  'num lock': Key.NumLock,
  // "": Key.AudioMute,
  // "": Key.AudioVolDown,
  // "": Key.AudioVolUp,
  // "": Key.AudioPlay,
  // "": Key.AudioStop,
  // "": Key.AudioPause,
  // "": Key.AudioPrev,
  // "": Key.AudioNext,
  // "": Key.AudioRewind,
  // "": Key.AudioForward,
  // "": Key.AudioRepeat,
  // "": Key.AudioRandom,
};

export const s2k = (s: string): Key => map[s];
