name: 'Build and release electron installer'
on:
  push:
    branches:
      - 'vtest'
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix: # M1 Macも必要。
        os: [macos-latest, windows-latest]
      fail-fast: false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}

          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
