name: 'Build and release electron installer'
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'

      - name: Build/release Electron app
        run: |
          npm i
          npm run preprocess
          export CSC_LINK="$MAC_CERTS"
          export CSC_KEY_PASSWORD="$MAC_CERTS_PASSWORD"
          ./node_modules/.bin/electron-builder --mac --x64 --publish=always
          ./node_modules/.bin/electron-builder --mac --arm64 --publish=always
          export CSC_LINK="$WINDOWS_CERTS"
          export CSC_KEY_PASSWORD="$WINDOWS_CERTS_PASSWORD"
          ./node_modules/.bin/electron-builder --windows --x64 --publish=always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
          ASC_PROVIDER: ${{ secrets.ASC_PROVIDER }}
          MAC_CERTS: ${{ secrets.MAC_CERTS }}
          MAC_CERTS_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
          WINDOWS_CERTS: ${{ secrets.WINDOWS_CERTS }}
          WINDOWS_CERTS_PASSWORD: ${{ secrets.WINDOWS_CERTS_PASSWORD }}
