name: 'Build and release electron installer'
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'

      - name: Build/release Electron app
        if: runner.os == 'macOS'
        run: |
          npm i
          npm run preprocess
          ./node_modules/.bin/electron-builder --mac --x64 --arm64 --publish=always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
          ASC_PROVIDER: ${{ secrets.ASC_PROVIDER }}
          CSC_LINK: ${{ secrets.MAC_CERTS }}
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}

      - name: Build/release Electron app
        if: runner.os == 'Windows'
        run: |
          npm i node-gyp
          npm i
          npm run preprocess
          ./node_modules/.bin/electron-builder --win --x64 --publish=always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.WINDOWS_CERTS }}
          CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_CERTS_PASSWORD }}
